version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:    
    commands:
      - sudo apt update
      - sudo npm install pm2 -g
  build:
    commands:
      - npm install 
artifacts:
  files:
    - '**/*'
